---
- name: "Assess: {{ checkref_1_1_1_4 }} {{ check_1_1_1_4 }} | configuration"
  when:
    - CISBenchUbuntu_1_1_1_4 | bool
  shell: "{{ assess_1_1_1_4_line }}"
  failed_when: false
  changed_when: false
  register: audit_1_1_1_4_assess

- name: "Remediate: {{ checkref_1_1_1_4 }} {{ check_1_1_1_4 }} | configuration"
  when:
    - CISBenchUbuntu_1_1_1_4 | bool
    - CISBenchUbuntu_Remediate | bool
    - calculate_1_1_1_4_assess | length == 0
  lineinfile:
    path: "{{ remediate_1_1_1_4_path }}"
    line: "{{ remediate_1_1_1_4_line }}"
    owner: root
    group: root
    mode: "0640"
    create: yes
  register: remediate_1_1_1_4_config_file

- name: "Audit: {{ checkref_1_1_1_4 }} {{ check_1_1_1_4 }} | report"
  when: CISBenchUbuntu_1_1_1_4 | bool
  include_tasks: AUDIT.yml
  vars:
    checkref: "{{ checkref_1_1_1_4 | default('') }}"
    checktitle: "{{ check_1_1_1_4 | default('') }}"
    checkresult: "{{ audit_1_1_1_4 | default('') }}"
    evidence: "{{ audit_1_1_1_4_evidence | default('') }}"
    remediation: "{{ audit_1_1_1_4_remediation | default('') }}"
    remediationperformed: "{{ audit_1_1_1_4_remediationperformed | default('') }}"